import type { Metadata } from "next";
import "@/app/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import NextAuthWrapper from "./utils/next.auth.wrapper";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <NextAuthWrapper>{children}</NextAuthWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
